/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rand.h"

void *
inicializa_random_1_svc(long *argp, struct svc_req *rqstp)
{
	static char * result;

	printf("Se llamo a inicializacion con la semilla %ld \n", *argp);
	srandom(*argp);
	 
 
	return (void *) &result;
	
}

double *
obtiene_siguiente_random_1_svc(void *argp, struct svc_req *rqstp)
{
	static double  result;

	  
	  result=random();
	  printf("Se genera un numero aleatorio, numero generado %.0f:\n ", result);

	return &result;
}
